import Foundation
import Testing
@testable import SwiftVerificarValidation

@Suite("RuleResult Tests")
struct RuleResultTests {

    // MARK: - Initialization Tests

    @Test("Create RuleResult with all parameters")
    func createWithAllParameters() {
        let id = UUID()
        let result = RuleResult(
            id: id,
            ruleId: "rule-001",
            status: .passed,
            message: "Rule passed successfully",
            context: "Page 1, Object 42"
        )

        #expect(result.id == id)
        #expect(result.ruleId == "rule-001")
        #expect(result.status == .passed)
        #expect(result.message == "Rule passed successfully")
        #expect(result.context == "Page 1, Object 42")
    }

    @Test("Create RuleResult with minimal parameters")
    func createWithMinimalParameters() {
        let result = RuleResult(
            ruleId: "rule-002",
            status: .failed
        )

        #expect(result.ruleId == "rule-002")
        #expect(result.status == .failed)
        #expect(result.message == nil)
        #expect(result.context == nil)
    }

    @Test("RuleResult ID is auto-generated")
    func autoGeneratedId() {
        let result1 = RuleResult(ruleId: "rule-1", status: .passed)
        let result2 = RuleResult(ruleId: "rule-2", status: .passed)

        #expect(result1.id != result2.id)
    }

    // MARK: - Status Tests

    @Test("RuleResult with passed status")
    func passedStatus() {
        let result = RuleResult(ruleId: "rule-1", status: .passed)
        #expect(result.status == .passed)
    }

    @Test("RuleResult with failed status")
    func failedStatus() {
        let result = RuleResult(ruleId: "rule-1", status: .failed)
        #expect(result.status == .failed)
    }

    @Test("RuleResult with warning status")
    func warningStatus() {
        let result = RuleResult(ruleId: "rule-1", status: .warning)
        #expect(result.status == .warning)
    }

    @Test("RuleResult with error status")
    func errorStatus() {
        let result = RuleResult(ruleId: "rule-1", status: .error)
        #expect(result.status == .error)
    }

    // MARK: - Message Tests

    @Test("RuleResult with message")
    func withMessage() {
        let result = RuleResult(
            ruleId: "rule-1",
            status: .failed,
            message: "Font not embedded"
        )

        #expect(result.message == "Font not embedded")
    }

    @Test("RuleResult without message")
    func withoutMessage() {
        let result = RuleResult(
            ruleId: "rule-1",
            status: .passed
        )

        #expect(result.message == nil)
    }

    // MARK: - Context Tests

    @Test("RuleResult with context")
    func withContext() {
        let result = RuleResult(
            ruleId: "rule-1",
            status: .failed,
            context: "Page 5, Font /F1"
        )

        #expect(result.context == "Page 5, Font /F1")
    }

    @Test("RuleResult without context")
    func withoutContext() {
        let result = RuleResult(
            ruleId: "rule-1",
            status: .passed
        )

        #expect(result.context == nil)
    }

    @Test("RuleResult with detailed context")
    func detailedContext() {
        let result = RuleResult(
            ruleId: "rule-font-001",
            status: .failed,
            message: "Font not embedded",
            context: "Page: 5, Object: 42, Font: /F1, Type: Type1"
        )

        #expect(result.context?.contains("Page: 5") == true)
        #expect(result.context?.contains("Object: 42") == true)
    }

    // MARK: - Identifiable Conformance

    @Test("RuleResult conforms to Identifiable")
    func conformsToIdentifiable() {
        let result = RuleResult(ruleId: "rule-1", status: .passed)
        let id: UUID = result.id
        #expect(id == result.id)
    }

    @Test("Multiple results have unique IDs")
    func uniqueIds() {
        let results = (1...10).map { i in
            RuleResult(ruleId: "rule-\(i)", status: .passed)
        }

        let ids = results.map { $0.id }
        let uniqueIds = Set(ids)

        #expect(ids.count == uniqueIds.count)
    }

    // MARK: - Sendable Conformance

    @Test("RuleResult is Sendable")
    func isSendable() {
        let result = RuleResult(ruleId: "rule-1", status: .passed)

        Task {
            let _ = result
            #expect(true)
        }
    }

    // MARK: - Combined Tests

    @Test("Failed result with message and context")
    func failedWithDetails() {
        let result = RuleResult(
            ruleId: "6.2.11.7-1",
            status: .failed,
            message: "All non-symbolic TrueType fonts shall specify Encoding or ToUnicode",
            context: "Page 1, Font /F3"
        )

        #expect(result.status == .failed)
        #expect(result.message != nil)
        #expect(result.context != nil)
    }

    @Test("Warning result with message")
    func warningWithMessage() {
        let result = RuleResult(
            ruleId: "metadata-001",
            status: .warning,
            message: "XMP metadata missing recommended fields"
        )

        #expect(result.status == .warning)
        #expect(result.message != nil)
    }

    @Test("Error result with context")
    func errorWithContext() {
        let result = RuleResult(
            ruleId: "structure-001",
            status: .error,
            context: "Document root"
        )

        #expect(result.status == .error)
        #expect(result.context != nil)
    }

    // MARK: - Explanation Tests

    @Test("RuleResult with explanation")
    func withExplanation() {
        let result = RuleResult(
            ruleId: "rule-001",
            status: .failed,
            message: "Test failed",
            explanation: "Detailed explanation of the failure"
        )

        #expect(result.explanation == "Detailed explanation of the failure")
    }

    @Test("RuleResult without explanation")
    func withoutExplanation() {
        let result = RuleResult(
            ruleId: "rule-001",
            status: .passed
        )

        #expect(result.explanation == nil)
    }

    @Test("Failed result with message, context, and explanation")
    func failedWithAllDetails() {
        let result = RuleResult(
            ruleId: "6.2.11.7-1",
            status: .failed,
            message: "Font encoding missing",
            context: "Page 1, Font /F3",
            explanation: "Rule 6.2.11.7-1 requires all TrueType fonts to have encoding"
        )

        #expect(result.status == .failed)
        #expect(result.message != nil)
        #expect(result.context != nil)
        #expect(result.explanation != nil)
        #expect(result.explanation?.contains("6.2.11.7-1") == true)
    }
}
