import Foundation
#if canImport(SwiftVerificarParser)
import SwiftVerificarParser
#endif

// MARK: - Form Field Type

/// Enumeration of AcroForm field types.
///
/// Corresponds to the `/FT` (field type) entry in a form field dictionary.
public enum FormFieldType: String, Sendable, Hashable, CaseIterable, Codable {
    /// Text field (`Tx`).
    case text = "Tx"

    /// Button field (`Btn`) -- push button, checkbox, or radio button.
    case button = "Btn"

    /// Choice field (`Ch`) -- combo box or list box.
    case choice = "Ch"

    /// Signature field (`Sig`).
    case signature = "Sig"

    /// Creates a form field type from a string.
    ///
    /// - Parameter value: The field type string (e.g., "Tx", "Btn").
    /// - Returns: The matching form field type, or `nil` if unrecognized.
    public static func from(_ value: String) -> FormFieldType? {
        FormFieldType(rawValue: value)
    }
}

// MARK: - Validated AcroForm

/// A validation wrapper for a PDF interactive form (AcroForm).
///
/// This struct wraps the AcroForm dictionary for validation purposes, providing
/// access to form-level properties and field information. AcroForms define
/// interactive form fields in PDF documents.
///
/// ## Key Properties
///
/// - **Fields**: The form field collection
/// - **Default Resources**: Resources shared by all fields
/// - **NeedAppearances**: Whether appearances need regeneration
/// - **SignatureFlags**: Signature-related flags
///
/// ## Validation Rules
///
/// - **PDF/A**: `NeedAppearances` must be `false` (or absent) -- appearances must
///   be embedded, not regenerated by the viewer.
/// - **PDF/UA**: All form fields must be accessible (tagged, with tooltips).
/// - **PDF/A-1**: Digital signature fields have specific requirements.
///
/// ## Relationship to veraPDF
///
/// Corresponds to `GFPDAcroForm` from veraPDF-validation.
///
/// ## Swift Adaptations
///
/// - Value type (struct) for thread safety
/// - Sendable for concurrent validation
/// - Consolidates form field analysis methods
public struct ValidatedAcroForm: PDValidationObject, Sendable, Equatable {

    // MARK: - Properties

    /// Unique identifier for this validation object.
    public let id: UUID

    /// The underlying COS dictionary for the AcroForm.
    public let cosDictionary: COSValue?

    /// The object key for the AcroForm, if indirect.
    public let objectKey: COSObjectKey?

    /// The object context for validation reporting.
    public let validationContext: ObjectContext

    // MARK: - Form Properties

    /// The total number of form fields.
    public let fieldCount: Int

    /// Whether the `NeedAppearances` flag is set to `true`.
    ///
    /// If `true`, the viewer should regenerate appearance streams for form fields.
    /// This is **not permitted** in PDF/A-compliant documents.
    public let needAppearances: Bool

    /// The signature flags value (`/SigFlags` entry).
    ///
    /// Bit 1 (value 1): SignaturesExist -- at least one signature field exists.
    /// Bit 2 (value 2): AppendOnly -- the document should be appended to, not rewritten.
    public let signatureFlags: Int

    /// Whether the form has a default appearance string (`/DA` entry).
    public let hasDefaultAppearance: Bool

    /// The default appearance string, if present.
    public let defaultAppearance: String?

    /// Whether the form has a default resources dictionary (`/DR` entry).
    public let hasDefaultResources: Bool

    /// Whether the form has a calculation order array (`/CO` entry).
    public let hasCalculationOrder: Bool

    /// The number of entries in the calculation order array.
    public let calculationOrderCount: Int

    /// Whether the form has an XFA (XML Forms Architecture) stream or array.
    ///
    /// XFA forms are **not permitted** in PDF/A-2 and later, and are discouraged
    /// in PDF 2.0.
    public let hasXFA: Bool

    // MARK: - Field Analysis

    /// The number of text fields.
    public let textFieldCount: Int

    /// The number of button fields (push buttons, checkboxes, radio buttons).
    public let buttonFieldCount: Int

    /// The number of choice fields (combo boxes, list boxes).
    public let choiceFieldCount: Int

    /// The number of signature fields.
    public let signatureFieldCount: Int

    /// Whether the form has any signature fields.
    public var hasSignatureFields: Bool {
        signatureFieldCount > 0
    }

    /// Whether the signatures exist flag is set.
    public var signaturesExist: Bool {
        signatureFlags & 1 != 0
    }

    /// Whether the append-only flag is set.
    public var isAppendOnly: Bool {
        signatureFlags & 2 != 0
    }

    // MARK: - Initialization

    /// Creates a validated AcroForm.
    ///
    /// - Parameters:
    ///   - id: Unique identifier. Defaults to a new UUID.
    ///   - cosDictionary: The COS dictionary for the AcroForm.
    ///   - objectKey: The object key for the AcroForm.
    ///   - context: Validation context.
    ///   - fieldCount: Total number of form fields.
    ///   - needAppearances: Whether NeedAppearances is set.
    ///   - signatureFlags: The SigFlags value.
    ///   - hasDefaultAppearance: Whether DA exists.
    ///   - defaultAppearance: The DA string.
    ///   - hasDefaultResources: Whether DR exists.
    ///   - hasCalculationOrder: Whether CO exists.
    ///   - calculationOrderCount: Number of CO entries.
    ///   - hasXFA: Whether XFA is present.
    ///   - textFieldCount: Number of text fields.
    ///   - buttonFieldCount: Number of button fields.
    ///   - choiceFieldCount: Number of choice fields.
    ///   - signatureFieldCount: Number of signature fields.
    public init(
        id: UUID = UUID(),
        cosDictionary: COSValue? = nil,
        objectKey: COSObjectKey? = nil,
        context: ObjectContext = ObjectContext(location: "AcroForm"),
        fieldCount: Int = 0,
        needAppearances: Bool = false,
        signatureFlags: Int = 0,
        hasDefaultAppearance: Bool = false,
        defaultAppearance: String? = nil,
        hasDefaultResources: Bool = false,
        hasCalculationOrder: Bool = false,
        calculationOrderCount: Int = 0,
        hasXFA: Bool = false,
        textFieldCount: Int = 0,
        buttonFieldCount: Int = 0,
        choiceFieldCount: Int = 0,
        signatureFieldCount: Int = 0
    ) {
        self.id = id
        self.cosDictionary = cosDictionary
        self.objectKey = objectKey
        self.validationContext = context
        self.fieldCount = fieldCount
        self.needAppearances = needAppearances
        self.signatureFlags = signatureFlags
        self.hasDefaultAppearance = hasDefaultAppearance
        self.defaultAppearance = defaultAppearance
        self.hasDefaultResources = hasDefaultResources
        self.hasCalculationOrder = hasCalculationOrder
        self.calculationOrderCount = calculationOrderCount
        self.hasXFA = hasXFA
        self.textFieldCount = textFieldCount
        self.buttonFieldCount = buttonFieldCount
        self.choiceFieldCount = choiceFieldCount
        self.signatureFieldCount = signatureFieldCount
    }

    // MARK: - PDFObject Conformance

    /// The object type for validation profiles.
    public var objectType: String {
        "PDAcroForm"
    }

    /// Property names supported by this object.
    public var propertyNames: [String] {
        [
            "fieldCount", "needAppearances", "signatureFlags",
            "hasDefaultAppearance", "defaultAppearance",
            "hasDefaultResources", "hasCalculationOrder",
            "calculationOrderCount", "hasXFA",
            "textFieldCount", "buttonFieldCount",
            "choiceFieldCount", "signatureFieldCount",
            "hasSignatureFields", "signaturesExist", "isAppendOnly",
            "hasFields", "isPDFACompliant"
        ]
    }

    /// Returns the value of a property by name.
    ///
    /// - Parameter name: The property name.
    /// - Returns: The property value, or `nil` if not found.
    public func property(named name: String) -> PropertyValue? {
        switch name {
        case "fieldCount":
            return .integer(Int64(fieldCount))
        case "needAppearances":
            return .boolean(needAppearances)
        case "signatureFlags":
            return .integer(Int64(signatureFlags))
        case "hasDefaultAppearance":
            return .boolean(hasDefaultAppearance)
        case "defaultAppearance":
            if let da = defaultAppearance {
                return .string(da)
            }
            return .null
        case "hasDefaultResources":
            return .boolean(hasDefaultResources)
        case "hasCalculationOrder":
            return .boolean(hasCalculationOrder)
        case "calculationOrderCount":
            return .integer(Int64(calculationOrderCount))
        case "hasXFA":
            return .boolean(hasXFA)
        case "textFieldCount":
            return .integer(Int64(textFieldCount))
        case "buttonFieldCount":
            return .integer(Int64(buttonFieldCount))
        case "choiceFieldCount":
            return .integer(Int64(choiceFieldCount))
        case "signatureFieldCount":
            return .integer(Int64(signatureFieldCount))
        case "hasSignatureFields":
            return .boolean(hasSignatureFields)
        case "signaturesExist":
            return .boolean(signaturesExist)
        case "isAppendOnly":
            return .boolean(isAppendOnly)
        case "hasFields":
            return .boolean(hasFields)
        case "isPDFACompliant":
            return .boolean(isPDFACompliant)
        default:
            return nil
        }
    }

    // MARK: - Equatable

    public static func == (lhs: ValidatedAcroForm, rhs: ValidatedAcroForm) -> Bool {
        lhs.id == rhs.id
    }
}

// MARK: - Computed Properties

extension ValidatedAcroForm {

    /// Whether the form has any fields.
    public var hasFields: Bool {
        fieldCount > 0
    }

    /// Whether the form is empty (no fields).
    public var isEmpty: Bool {
        fieldCount == 0
    }

    /// Whether the form meets basic PDF/A compliance requirements.
    ///
    /// For PDF/A, the form must not require appearance regeneration
    /// and must not contain XFA data.
    public var isPDFACompliant: Bool {
        !needAppearances && !hasXFA
    }

    /// Returns a summary string describing the AcroForm.
    public var summary: String {
        var parts: [String] = ["\(fieldCount) fields"]
        if textFieldCount > 0 { parts.append("\(textFieldCount) text") }
        if buttonFieldCount > 0 { parts.append("\(buttonFieldCount) buttons") }
        if choiceFieldCount > 0 { parts.append("\(choiceFieldCount) choices") }
        if signatureFieldCount > 0 { parts.append("\(signatureFieldCount) signatures") }
        if needAppearances { parts.append("needAppearances") }
        if hasXFA { parts.append("XFA") }
        return parts.joined(separator: ", ")
    }
}

// MARK: - Factory Methods

extension ValidatedAcroForm {

    /// Creates a minimal AcroForm for testing.
    ///
    /// - Parameters:
    ///   - fieldCount: Total number of fields.
    ///   - needAppearances: Whether NeedAppearances is set.
    /// - Returns: A minimal AcroForm.
    public static func minimal(
        fieldCount: Int = 0,
        needAppearances: Bool = false
    ) -> ValidatedAcroForm {
        ValidatedAcroForm(
            fieldCount: fieldCount,
            needAppearances: needAppearances
        )
    }

    /// Creates an AcroForm with signature fields for testing.
    ///
    /// - Parameters:
    ///   - signatureCount: Number of signature fields.
    ///   - signaturesExist: Whether the SignaturesExist flag is set.
    /// - Returns: An AcroForm with signatures.
    public static func withSignatures(
        signatureCount: Int = 1,
        signaturesExist: Bool = true
    ) -> ValidatedAcroForm {
        ValidatedAcroForm(
            fieldCount: signatureCount,
            signatureFlags: signaturesExist ? 1 : 0,
            signatureFieldCount: signatureCount
        )
    }
}
